/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	*(volatile uint32_t*) 0x40023830 |= (1 << 1);   // enable GPIOB clock
	*(volatile uint32_t*) 0x40020400 |= (1 << 17);  // PB8: alternate function
	*(volatile uint32_t*) 0x40020400 |= (1 << 19);  // PB9: alternate function
	*(volatile uint32_t*) 0x40020404 |= (1 << 8);   // PB8: open-drain
	*(volatile uint32_t*) 0x40020404 |= (1 << 9);   // PB9: open-drain
	*(volatile uint32_t*) 0x40020424 |= 4;          // PB8: AF4 (I2C1_SCL)
	*(volatile uint32_t*) 0x40020424 |= (4 << 4);   // PB9: AF4 (I2C1_SDA)
	*(volatile uint32_t*) 0x40023840 |= (1 << 21);  // enable I2C1 clock

	*(volatile uint32_t*) 0x40005404 |= 16;     // CR2: APB1 = 16 MHz
	*(volatile uint32_t*) 0x4000541C |= 0x50;   // CCR: 100kHz timing
	*(volatile uint32_t*) 0x40005420 |= 17;     // TRISE: rise-time compensation
	*(volatile uint32_t*) 0x40005400 |= (1<<0); // CR1: PE — enable, last

    /* Loop forever */
	for(;;);
}
